name: codecooo_csharp_rpc
description: Execute C# code from Dart (Flutter) application via JSON-RPC protocol.
version: 0.0.8
maintainer: Codecooo
homepage: https://github.com/Codecooo/FlutterSharpRpc
issue_tracker: https://github.com/Codecooo/FlutterSharpRpc/issues
screenshots:
  - description: "Execute C# code from Dart (Flutter) application."
    path: doc/assets/csharp_rpc_logo_small.png

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  uuid: ^4.5.2
  logging: ^1.2.0
  collection: ^1.17.0

dev_dependencies:
  flutter_lints: ^6.0.0
